title : "What Goes Into A Word: Generating Image Descriptions 
With Top-Down Spatial Knowledge"
description : "Mehdi Ghanimifard and Simon Dobnik
INLG 2019 Tokyo, Japan
29 October - 1 November 2019"
theme: minima
